Import('env')
Import('config')

env = env.Clone()
env.Append(CPPPATH=['#'], LIBPATH=['#'])
Export('env')

subdirs = [
	#'fxtest',
	'geometrytest',
	#'gfxtest',
	'mathtest',
	#'raytest',
	'realtest',
	#'signaltest',
	'systest',
]

env.SConscript(dirs=subdirs)
