% Description: PastelGeometryMatlab mex debug building

mex pastelgeometrymatlab.cpp ...
    -D_HAS_ITERATOR_DEBUGGING=0 ...
    -I'..\..\..\pastel\' ...
    -I'..\..\..\..\external\boost_1_45_0\' ...
    -L'..\..\..\pastel\build\vs2008\lib\' ...
    -lPastelSys_d ...
    -lPastelMatlab_d ...
    -lPastelMath_d ...
    -lPastelGeometry_d ...
    -lPastelGeometryMatlab_d ...
    -g
