% Description: PastelGeometryMatlab release build script

mex pastelgeometrymatlab.cpp ...
    -D_HAS_ITERATOR_DEBUGGING=0 ...
    -DPASTEL_ENABLE_OMP ...
    -I'..\..\..\pastel\' ...
    -I'..\..\..\..\external\boost_1_49_0\' ...
    -L'..\..\..\pastel\build\vs2010\lib\release\' ...
    -lPastelGeometryMatlab ...
    -lPastelGeometry ...
    -lPastelMath ...
    -lPastelMatlab ...
    -lPastelSys
