% Description: PastelGeometryMatlab debug build script

mex pastelgeometrymatlab.cpp ...
    -D_ITERATOR_DEBUG_LEVEL=0 ...
    -I'..\..\..\pastel\' ...
    -I'..\..\..\..\external\boost_1_51_0\' ...
    -L'..\..\..\pastel\build\vs2010\lib\debug\' ...
    -lPastelGeometryMatlab ...
    -lPastelGeometry ...
    -lPastelMath ...
    -lPastelMatlab ...
    -lPastelSys ...
    -g
