% Description: PastelGeometryMatlab mex building

mex pastelgeometrymatlab.cpp ...
    -D_HAS_ITERATOR_DEBUGGING=0 ...
    -DPASTEL_ENABLE_OMP ...
    -I'..\..\..\pastel\' ...
    -I'..\..\..\..\external\boost_1_45_0\' ...
    -L'..\..\..\pastel\build\vs2008\lib\' ...
    -lPastelSys ...
    -lPastelMatlab ...
    -lPastelMath ...
    -lPastelGeometry ...
    -lPastelGeometryMatlab
