% Description: PastelGeometryMatlab release-without-openmp build script

mex pastelgeometrymatlab.cpp ...
    -D_HAS_ITERATOR_DEBUGGING=0 ...
    -I'..\..\..\pastel\' ...
    -I'..\..\..\..\external\boost_1_49_0\' ...
    -L'..\..\..\pastel\build\vs2010\lib\release-without-openmp\' ...
    -lPastelGeometryMatlab ...
    -lPastelGeometry ...
    -lPastelMath ...
    -lPastelMatlab ...
    -lPastelSys
