Import('env')

env = env.Clone()
env.Append(LIBS='pastel')
env.Append(CXXFLAGS=' -g')

src = [
	'pastelsystest.cpp',
	'testarenaallocator.cpp',
	'testarray2.cpp',
	'testdefaultdata.cpp',
	'testendian.cpp',
	#'testfastlist.cpp',
	'testindexallocator.cpp',
	'testparallelarray.cpp',
	'testpoolallocator.cpp',
	'testsmallmap.cpp',
	'testsmallset.cpp',
	'testunordered_set.cpp',
]

objs = []
for filename in src:
	objs += env.StaticObject(source=filename)

env.Program(target='pastelsystest', source=objs)
