Import('env')

env = env.Clone()
env.Append(LIBS='pastel')
env.Append(CXXFLAGS=' -g')

src = [
	'mathinstantiate.cpp',
	'pastelmathtest.cpp',
	'testmatrix.cpp',
	'testvector.cpp',
]

objs = []
for filename in src:
	objs += env.StaticObject(source=filename)

env.Program(target='pastelmathtest', source=objs)
